//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tixxp.WebApp.Resources.Views.TicketSale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Confirmation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Confirmation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tixxp.WebApp.Resources.Views.TicketSale._Confirmation", typeof(_Confirmation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Details Page.
        /// </summary>
        internal static string confirmation_BACK {
            get {
                return ResourceManager.GetString("confirmation.BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Discounted Amount.
        /// </summary>
        internal static string confirmation_CAMPAIGN_TOTAL {
            get {
                return ResourceManager.GetString("confirmation.CAMPAIGN_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        internal static string confirmation_CAMPAIGNS {
            get {
                return ResourceManager.GetString("confirmation.CAMPAIGNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Empty.
        /// </summary>
        internal static string confirmation_CART_EMPTY {
            get {
                return ResourceManager.GetString("confirmation.CART_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Summary.
        /// </summary>
        internal static string confirmation_CART_SUMMARY {
            get {
                return ResourceManager.GetString("confirmation.CART_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cart.
        /// </summary>
        internal static string confirmation_CLEAR_CART {
            get {
                return ResourceManager.GetString("confirmation.CLEAR_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Sale.
        /// </summary>
        internal static string confirmation_CONFIRM_SALE {
            get {
                return ResourceManager.GetString("confirmation.CONFIRM_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string confirmation_ORIGINAL_TOTAL {
            get {
                return ResourceManager.GetString("confirmation.ORIGINAL_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece.
        /// </summary>
        internal static string confirmation_PIECE {
            get {
                return ResourceManager.GetString("confirmation.PIECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string confirmation_PRODUCT {
            get {
                return ResourceManager.GetString("confirmation.PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string confirmation_SUBTOTAL {
            get {
                return ResourceManager.GetString("confirmation.SUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string confirmation_TOTAL {
            get {
                return ResourceManager.GetString("confirmation.TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string confirmation_UNIT_PRICE {
            get {
                return ResourceManager.GetString("confirmation.UNIT_PRICE", resourceCulture);
            }
        }
    }
}
