//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tixxp.WebApp.Resources.Views.TicketSale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tixxp.WebApp.Resources.Views.TicketSale._Details", typeof(_Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string details_ACTION {
            get {
                return ResourceManager.GetString("details.ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        internal static string details_ADD_TO_CART {
            get {
                return ResourceManager.GetString("details.ADD_TO_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string details_CANCEL {
            get {
                return ResourceManager.GetString("details.CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string details_CART {
            get {
                return ResourceManager.GetString("details.CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string details_CART_DETAIL {
            get {
                return ResourceManager.GetString("details.CART_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string details_CITY {
            get {
                return ResourceManager.GetString("details.CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string details_CONFIRMATION {
            get {
                return ResourceManager.GetString("details.CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string details_COUNTRY {
            get {
                return ResourceManager.GetString("details.COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string details_COUNTY {
            get {
                return ResourceManager.GetString("details.COUNTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        internal static string details_CURRENCY_TYPE {
            get {
                return ResourceManager.GetString("details.CURRENCY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string details_E_MAIL {
            get {
                return ResourceManager.GetString("details.E_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@email.com.
        /// </summary>
        internal static string details_E_MAIL_PLACEHOLDER {
            get {
                return ResourceManager.GetString("details.E_MAIL_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string details_FIRST_NAME {
            get {
                return ResourceManager.GetString("details.FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string details_LAST_NAME {
            get {
                return ResourceManager.GetString("details.LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string details_LASTNAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("details.LASTNAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string details_NAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("details.NAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ticket For Session.
        /// </summary>
        internal static string details_NO_TICKET_FOR_SESSION {
            get {
                return ResourceManager.GetString("details.NO_TICKET_FOR_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        internal static string details_PAYMENT_INFORMATION {
            get {
                return ResourceManager.GetString("details.PAYMENT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        internal static string details_PAYMENT_TYPE {
            get {
                return ResourceManager.GetString("details.PAYMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string details_PERSONAL_INFORMATION {
            get {
                return ResourceManager.GetString("details.PERSONAL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string details_PHONE {
            get {
                return ResourceManager.GetString("details.PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece.
        /// </summary>
        internal static string details_PIECE {
            get {
                return ResourceManager.GetString("details.PIECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string details_PRODUCT {
            get {
                return ResourceManager.GetString("details.PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Information.
        /// </summary>
        internal static string details_TICKET_INFORMATION {
            get {
                return ResourceManager.GetString("details.TICKET_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Total.
        /// </summary>
        internal static string details_TICKET_TOTAL {
            get {
                return ResourceManager.GetString("details.TICKET_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Type.
        /// </summary>
        internal static string details_TICKET_TYPE {
            get {
                return ResourceManager.GetString("details.TICKET_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string details_TOTAL_AMOUNT {
            get {
                return ResourceManager.GetString("details.TOTAL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string details_UNIT_PRICE {
            get {
                return ResourceManager.GetString("details.UNIT_PRICE", resourceCulture);
            }
        }
    }
}
