//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tixxp.WebApp.Resources.Views.TicketSale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tixxp.WebApp.Resources.Views.TicketSale.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Success.
        /// </summary>
        internal static string confirmation_SUCCESS {
            get {
                return ResourceManager.GetString("confirmation.SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ticketSale_INDEX_BACK {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Time.
        /// </summary>
        internal static string ticketSale_INDEX_CLOSING {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.CLOSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ticketSale_INDEX_CONFIRMATION {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        internal static string ticketSale_INDEX_DATE {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string ticketSale_INDEX_DETAILS {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string ticketSale_INDEX_EVENT {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple currencies available. Details in the totals section above..
        /// </summary>
        internal static string ticketSale_INDEX_MULTIPLE_CURRENCIES {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.MULTIPLE_CURRENCIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found.
        /// </summary>
        internal static string ticketSale_INDEX_NO_EVENTS {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.NO_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Time.
        /// </summary>
        internal static string ticketSale_INDEX_OPENING {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Ticket.
        /// </summary>
        internal static string ticketSale_INDEX_SELL_TICKET {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.SELL_TICKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        internal static string ticketSale_INDEX_SESSION {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        internal static string ticketSale_INDEX_TOTALS {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.TOTALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sessions.
        /// </summary>
        internal static string ticketSale_INDEX_VIEW_SESSIONS {
            get {
                return ResourceManager.GetString("ticketSale.INDEX.VIEW_SESSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        internal static string ticketSale_SELECT_CITY {
            get {
                return ResourceManager.GetString("ticketSale.SELECT_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string ticketSale_SELECT_COUNTRY {
            get {
                return ResourceManager.GetString("ticketSale.SELECT_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select County.
        /// </summary>
        internal static string ticketSale_SELECT_COUNTY {
            get {
                return ResourceManager.GetString("ticketSale.SELECT_COUNTY", resourceCulture);
            }
        }
    }
}
